version: '3'

services:
  builder:
    container_name: hush-builder
    build:
      context: ./build/builder
    volumes:
      - ./hush.db:/tmp/hush.db:rw
      - ./src/:/app/:rw
      - ./build/php/php.local.ini:/usr/local/etc/php/php.ini:ro
  php:
    container_name: hush-php
    build:
      context: ./build/php
    volumes:
      - ./hush.db:/tmp/hush.db:rw
      - ./src/:/app/:ro
      - ./src/vendor/:/app/vendor/:rw
      - ./src/bootstrap/cache/:/app/bootstrap/cache/:rw
      - ./src/storage/:/app/storage/:rw
      - ./build/php/php.local.ini:/usr/local/etc/php/php.ini:ro
  www:
    container_name: hush-www
    image: nginx:1.14.0-alpine
    volumes:
      - ./src/:/app/:ro
      - ./build/www/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127.0.0.1:8080:80
