version: '3'

services:
  npm:
    container_name: hush-npm
    image: node:10.9.0-slim
    user: ${APP_UID}:${APP_GID}
    env_file:
      - .env
    working_dir: /app/
    command: bash -c "
      yarn install &&
      ${NPM_COMMAND}"
    volumes:
      - ./src/:/app/
  composer:
    container_name: hush-composer
    image: composer:1.7.2
    user: ${APP_UID}:${APP_GID}
    working_dir: /app/
    command: composer install
    volumes:
      - ./src/:/app/
  db:
    container_name: hush-db
    image: mariadb:10.3.9
    env_file:
      - .env
    volumes:
      - ./db_store/:/var/lib/mysql/
  php:
    container_name: hush-php
    build:
      context: ./build
      dockerfile: php.docker
    user: ${APP_UID}:${APP_GID}
    env_file:
      - .env
    volumes:
      - ./src/:/app/:ro
      - ./src/bootstrap/cache/:/app/bootstrap/cache/:rw
      - ./src/storage/:/app/storage/:rw
      - ./build/php.${APP_ENV}.ini:/usr/local/etc/php/php.ini:ro
  www:
    container_name: hush-www
    build:
      context: ./build
      dockerfile: www.docker
    volumes:
      - ./src/:/app/:ro
      - ./build/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '${APP_PORT}:80'
